project:
  type: manuscript
  
preview:
  watch: "content/*.qmd"
  watch-inputs: true
  port: 4040

manuscript:
  article: index.qmd

execute:
  freeze: auto

format:
  html:
    theme: flatly
    code-fold: true
  pdf:
    documentclass: scrreprt
#    lof: true
#    lot: true
    toc: true    
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    hyperrefoptions:
      - linktoc=all
    colorlinks: true
    linkcolor: "blue"
    biblio-style: ieee
    highlight-style: github
    mainfont: "Calibri"
#    keep-tex: true
    output-file: amcd_report 
#  epub:
#    theme: flatly
#    output-file: amcd_report
