# project:
#   type: manuscript
  
# manuscript:
#   article: index.qmd

project:
  type: book
  output-dir: _book

book:
  chapters:
    - index.qmd
    - content/_sec_introduction.qmd
    - content/_sec_theoretical_background.qmd
    - content/_sec_characterisation.qmd
    - content/_sec_filter-design.qmd        
    - content/_sec_discussion.qmd
    - content/_sec_conclusion-outlook.qmd
    - content/references.qmd
    
bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme: flatly
    code-fold: true
  pdf:
    documentclass: scrbook
#    lof: true
#    lot: true
    toc: true    
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    hyperrefoptions:
      - linktoc=all
    colorlinks: true
    linkcolor: "blue"
    biblio-style: ieee
    highlight-style: github
    mainfont: "Calibri"
#    keep-tex: true
#    output-file: amcd_report 
#  epub:
#    theme: flatly
#    output-file: amcd_report
