---
title: "IC Design of a Universal Biquad Filter"
author: 
  - name: Atakan Baydogan
    orcid: 
    email: abaydogan@stud.hs-bremen.de
    corresponding: true
    roles: "Lead author"
    # affiliation:
    #  - name: Hochschule Bremen - City University of Applied Sciences (HSB)
    #    city: Bremen
    #    state: Germany
    #    url: https://www.hs-bremen.de  
  - name: Onno Kriens
    orcid: 
    email: okriens@stud.hs-bremen.de
    corresponding: true
    roles: "Lead author"
  - name: Finn Ringelsiep
    orcid: 
    email: fringelsiep@stud.hs-bremen.de
    corresponding: true
    roles: "Lead author"
  - name: Alicia von Ahlen
    orcid: 0009-0007-3049-2455
    email: avahlen@stud.hs-bremen.de
    corresponding: true
    roles: "Lead author"

keyword:
  - Filter Design 
  - PCB

abstract: |
    Lorem ipsum Pipsum

    - An abstract should provide a self-contained summary of your entire paper or research project.
    - It aims to give readers a quick understanding of what you did, why it's important, and what you found. 
    - It should be a good starting point for anyone considering reading your full work. 
    - Introduction: Briefly introduce the topic and its significance.
    - Research Question/Aim: State the problem you are addressing and the purpose of your research.
    - Methodology: Briefly describe how you conducted your research (e.g., experiments, interviews, analysis).
    - Key Findings: Summarize the main results or conclusions of your study.
    - Significance/Implications: Explain why your findings are important and what they contribute to the field. 
    - Be concise: Use short, clear sentences and avoid unnecessary jargon. 
    - Use keywords: Include relevant keywords that will help readers find your abstract in databases. 
    - Follow formatting guidelines: Check for any specific requirements or guidelines for your specific journal or conference. 
    - Revise and edit: Make sure your abstract is clear, accurate, and within the word limit. 
    - Consider the audience: Tailor your language to your target audience (e.g., other researchers in your field, or a wider audience).

date: last-modified
number-sections: true
bibliography: references.bib
---

# TOC (only temporary) {.unnumbered}

- abstract
- introduction (motivation, goals, requirements, restrictions)
- filter design (theoretical background, methods)
- characterisation (filter requirements, theory in python, ideal circuit)
- design (real circuit, xschem, klayout)
- discussion
- conclusion



## Gliederung Vorschlag (Atakan)

1. Abstract

2. Introduction

3. Theoretical background 
   3.1 OTA
   3.2 Miller / 2order /biquard
   3.3 system overview
   3.4 methods

4. Charactaristic
    4.1 req
    4.2 python
    4.5 LTspice 

5. IC design
    5.1 ideal
    5.2 gm/id
    5.3 real 

6. Klayout

7. Discussion

8. Conclusion

## ONNO

1. Abstract

2. Intruduction

3. Theoretical View
	3.1 (OP)
	3.2 OTA
	3.3 Biasing
	3.4 Biquad

4. Top_Level (ASLK)
	4.1 Simulation
		4.1.1 Python
		4.1.2 PSpice
		4.1.3 Xschem

5. Bauteilebene
	5.1 Intruduction (Pretl)
	5.2 Parameters
	5.2 Xschem
	5.3 Miller

6. IC-Design
	K_Layout
7. Discussion



## TOC suggestion (Main)

1. Abstract (max. 0,5 page)

2. Introduction (1 page)

2.1 Motivation
2.2 Scope
2.3 Constraints (Meiners Kram)

3. Theoretical Background
3.1 Opamp
3.1.1 Current Mirror
3.1.2 Diff Stage
3.1.2 Variants (like Miller maybe?)
3.1.3 Small signal representation
3.1.4 Stability
3.1.5 Sizing?
3.2 Biquad
3.2.1 Characteristics
3.2.2 Stability

4. Characterisation
4.1 Behavioural analysis
4.1.1 Python
4.1.2 Ideal Opamp?
4.2 Implementation (real circuit)
4.2.1 Used opamp representation
4.2.2 Sizing

5. Design 
5.1 methods
5.1.1 Xschem
5.1.2 ngspice
5.1.3 KLayout 
5.2 Process) siehe finn

6. Discussion
6.1 Stability Analysis
6.2 Comparison
6.2.1 Python
6.2.2 Ideal
6.2.3 Real
6.3 is filter good?

7. Conclusion and outlook


<!-- {{< include content/_sec_introduction.qmd >}} -->

<!-- {{< include content/_sec_theoretical_background.qmd >}} -->

<!-- {{< include content/_sec_characterisation.qmd >}} -->

<!-- {{< include content/_sec_filter-design.qmd >}} -->

<!-- {{< include content/_sec_discussion.qmd >}} -->

<!-- {{< include content/_sec_conclusion-outlook.qmd >}} -->

<!-- {{< include content/references.qmd >}} -->
