project:
  type: manuscript
  title: "IIC design of a biquad filter"
  output-dir: _manuscript

lang: en

bibliography: references.bib

title: IIC design of a biquad filter
author:
  - name: Alicia von Ahlen
    orcid: 0009-0007-3049-2455
    email: avahlen@stud.hs-bremen.de
    roles: "Co-Author"
    #affiliation:
    #  - name: Hochschule Bremen - City University of Applied Sciences
    #    city: Bremen
    #    state: Germany
    #    url: https://www.hs-bremen.de/die-hsb/fakultaeten/elektrotechnik-und-informatik/forschung-und-transfer/institut-fuer-nachrichtentechnik/
  - name: Onno Kriens
    email: okriens@stud.hs-bremen.de
    roles: "Co-Author"
  - name: Finn Ringelsiep
    email: fringelsiep@stud.hs-bremen.de
    roles: "Co-Author"
  - name: Atakan Baydogan
    email: abaydogan@stud.hs-bremen.de
    roles: "Co-Author"

license: "Apache-2.0 license"
copyright:
  holder: "Onno Kriens, Alicia von Ahlen, Finn Ringelsiep und Atakan Baydogan, Hochschule Bremen."
  year: 2024-2025

date: today
date-format: iso

repo-url: https://github.com/avahlen/AMCD_Group1
#repo-branch: main
repo-actions: [edit, issue]
downloads: [pdf, epub]

website:
  navbar:
    search: true

format:
  html:
    toc: true
    toc-location: left
    toc-title: Contents
    toc-depth: 5
    toc-expand: 5
    number-sections: true
    fig-cap-location: bottom  # Bildunterschriften unter den Bildern anzeigen
    number-depth: 3
    code-fold: true
    default-fig-cap: "Figure"  # Automatische Nummerierung von Abbildungen
    css: styles.css
  pdf:
    documentclass: scrbook
    toc: true
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    hyperrefoptions: 
      - linktoc=all
    colorlinks: true
    linkcolor: "blue"
    biblio-style: ieee
    highlight-style: github
    mainfont: "Calibri"
    output-file: amcd
  epub: 
    theme: flatly
    output-file: amcd


execute:
  freeze: auto
