:::{.callout-important}
We need to go through the whole document and check whether opamp or ota is the right word in the context!

In the end we need to go through this, and change all second to last meantions of OP/operational amplifier to opamp 
:::

# TOC (only temporary) {.unnumbered}

- abstract
- introduction (motivation, goals, requirements, restrictions)
- filter design (theoretical background, methods)
- characterisation (filter requirements, theory in python, ideal circuit)
- design (real circuit, xschem, klayout)
- discussion
- conclusion



## Gliederung vorschlag (Atakan)

1 abstract
2 Introduction
3 Theoretical background 
    3.1 OTA
    3.2 Miller / 2order /biquard
    3.3 system overview
    3.4 methods
4 Charactaristic
    4.1 req
    4.2 python
    4.5 LTspice 
5 IC design
    5.1 ideal
    5.2 gm/id
    5.3 real 
6 klayout
6 discussion
7 conclusion

## ONNO

1. Abstract

2. Intruduction

3. Theoretical View
	3.1 (OP)
	3.2 OTA
	3.3 Biasing
	3.4 Biquad

4. Top_Level (ASLK)
	4.1 Simulation
		4.1.1 Python
		4.1.2 PSpice
		4.1.3 Xschem

5. Bauteilebene
	5.1 Intruduction (Pretl)
	5.2 Parameters
	5.2 Xschem
	5.3 Miller

6. IC-Design
	K_Layout
7. Discussion


## TOC suggestion (Main)

1 Abstract (max. 0,5 page)

2 Introduction (1 page)
2.1 Motivation
2.2 Scope
2.3 Constraints (Meiners Kram)

3 Theoretical Background
3.1 Opamp
3.1.1 Current Mirror
3.1.2 Diff Stage
3.1.2 Variants (like Miller maybe?)
3.1.3 Small signal representation
3.1.4 Stability
3.1.5 Sizing?
3.2 Biquad
3.2.1 Characteristics
3.2.2 Stability

4 Characterisation
4.1 Behavioural analysis
4.1.1 Python
4.1.2 Ideal Opamp?
4.2 Implementation (real circuit)
4.2.1 Used opamp representation
4.2.2 Sizing

(5 Design 
5.1 methods
5.1.1 Xschem
5.1.2 ngspice
5.1.3 KLayout 
5.2 Process) siehe finn

6 Discussion
6.1 Stability Analysis
6.2 Comparison
6.2.1 Python
6.2.2 Ideal
6.2.3 Real
6.3 is filter good?

7 Conclusion and outlook

# Introduction

:::{.callout-warning}
Check for reading flow please (for whole chapter)
:::

This chapter provides a short motivation and overview for the IC design process done during the lecture "Analogue and Digital Mixed-Signal Circuit Design" that Prof. Dr.-Ing. M. Meiners gives in the graduate course Electronic Engineering M.Sc. at City University of Applied Sciences Bremen.

The chapter will start with the motivation behind the Biquad IC filter design, outline the scope of work of the project, and ends with giving concrete specifications for the implemented filter.

## Motivation

The design and implementation of analog filters is a cornerstone in signal processing, with applications ranging from audio processing to communication systems. Among these, second order filters, like the biquad filter, are versatile building blocks due to its ability to realize four types of second order filters - low pass, high pass, band pass, and band stop. This project focuses on the integrated circuit (IC) design of a biquad filter, to get insight into the theoretical and practical engineering considerations behind IC design.

For a deeper understanding of IC design, this project does not rely on off-the-shelf operational amplifiers for the filter design, but aims to implement the entire filter architecture at the transistor level. This approach not only deepens the understanding of analog filter behavior but also introduces the challenges and intricacies of IC design, such as layout constraints, power efficiency, and stability.

This project demonstrates the design process of IC design from theorectical modelling, over simulation and design constraints to prototyping and to learn hands-on experience with tools used during the design process.

## Scope of the project

The scope of this project is supposed to follow a real-world design flow, starting at a theorectical analysis of the specified filter and - in the best case - end in a tap-out of a prototype. If that stage is reached the prototype can be compared to the theorectical and simulation results obtained during the design process and checked for functionality.

As a tap-out of a prototype is fairly unrealistic in the time given, the goal is to simulate the specified filter with templates for operational amplifiers and base the IC layout on these templates.

All in all, this project includes a systems analysis if the specified filter, simulation results with ideal components and real components, taken from provided templates, and a physical layout prototype.

## Specifications

:::{.callout-warning}
Not sure if this is written in the correct time!?!
:::

The main onjective is to design a universal biquad filter, based on the filter design proposed in the ASLK PRO Board Manual from Texas Instruments [@aslkpro2012]. The biquad filter shall have the following specifications:

$$
f_0 = 1\,kHz
$$

$$
Q = 10
$$

The circuit design is done in **Xschem** and the simulation in **ngspice**. For the design on transistor level the 130nm CMOS technology **SG13G2** is used. All these tools and PDk are integrated into a docker image **IIC-OSIC-TOOLS** [@pretl_git2025] provided by Prof. Dr. Harald Pretl from Johannes Keplar University. 

This documentation provides a development report, which documents the design process with the taken steps and decisions made.

## Open-Source

All the results of this report and development approach to design a Biquad are publicly available on GitHub (LINK...). Everyone is invited and should feel free to use, change, and share this work. 
This whole course and project wouldn't be possible without the great Open-Source-Tools provided by the amazing community of layout designers, enthusiasts, and developers. 
Here a list with just a few of this programs: `IC-OSIC-TOOLS`, `IHP Open PDK`, `Linux`, `Docker`, `Xschem`, `ngspice`, `KLayout`, `Quarto`, `Pandoc`, `TexLive`, `Python`, `Git`, `CoCalc`,

### Hymne

In realms where code is free to fly,<br>
We build and share, our hearts reach high. <br>
No walls, no locks, our wisdom streams, <br>
In open light, we chase our dreams. <br>

So sing the joy, the thrill, the spark, <br>
In open source, we find our arc. <br>
Together strong, we rise, explore— <br>
In lines of code, forevermore. <br>
